### ISSUE TITLE
Lib broken on python2

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-lib-python#51] opened 2017-07-07 11:15 UTC
The lib seems to be broken on python2. At least the ramp.py example is not working. See https://forum.bitcraze.io/viewtopic.php?f=6&t=2522&e=1.

**Comment by krichardsson** [comment] 2017-10-19 16:59
I can not reproduce this problem. It might be related to that we don't stop threads cleanly when closing down, but since I can not reproduce the problem it is hard to find it. 
Feel free to re-open if you see this problem again.

**Closed by krichardsson** 2017-10-19 16:59 UTC
